/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: 'class',
  content: [
    './app/**/*.{js,jsx,ts,tsx}',
    './src/**/*.{js,jsx,ts,tsx}',
  ],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        serene: {
          surface: '#FCF9F1',
          'surface-container-lowest': '#FFFFFF',
          'surface-container-low': '#F6F3EB',
          'surface-container': '#F1EEE6',
          'surface-container-high': '#EBE8E0',
          'surface-container-highest': '#E5E2DA',
          primary: '#115086',
          'primary-container': '#3368A0',
          'on-primary': '#FFFFFF',
          'on-primary-container': '#D5E5FF',
          'primary-fixed': '#D2E4FF',
          'primary-fixed-dim': '#A0C9FF',
          'on-primary-fixed': '#001C37',
          secondary: '#22657F',
          'secondary-container': '#A2E0FE',
          'on-secondary': '#FFFFFF',
          'on-secondary-container': '#20647E',
          'secondary-fixed': '#BEE9FF',
          'secondary-fixed-dim': '#92CFEC',
          tertiary: '#3D524F',
          'tertiary-container': '#556A67',
          'tertiary-fixed': '#D0E7E3',
          'tertiary-fixed-dim': '#B4CBC7',
          'on-tertiary-fixed': '#0A1F1D',
          'on-tertiary': '#FFFFFF',
          'on-surface': '#1C1C17',
          'on-surface-variant': '#42474F',
          outline: '#727781',
          'outline-variant': '#C2C7D1',
          'hairline-border': 'rgba(51, 104, 160, 0.08)',
          'subtle-border': '#E3DFD5',
          error: '#BA1A1A',
          'error-container': '#FFDAD6',
          'on-error-container': '#93000A',
          'on-error': '#FFFFFF',
          success: '#10B981',
          'success-container': '#D1FAE5',
          warning: '#F59E0B',
          'warning-container': '#FEF3C7',
        },
      },
      spacing: {
        'serene-xs': '4px',
        'serene-sm': '8px',
        'serene-md': '16px',
        'serene-lg': '24px',
        'serene-xl': '32px',
        'serene-xxl': '40px',
      },
      borderRadius: {
        'serene-sm': '6px',
        'serene-md': '8px',
        'serene-lg': '12px',
        'serene-xl': '16px',
        'serene-xxl': '24px',
      },
    },
  },
  plugins: [],
};
